module.exports = {
  MAX_PLAYERS: 5,
  HAND_SIZE: 10,

  DECLARE_SAM_SECONDS: 15,

  POINT_PER_CARD: 1,
  POINT_PER_TWO_REMAINING: 3,
  CHOP_TWO_PENALTY_EACH: 5,
  CONG_PENALTY: 20,

  WHITE_WIN_ORDER: ["FOUR_2", "STRAIGHT_10", "FIVE_PAIRS"],
};

